title: "SQL Judo"
description: "Гнучкий шлях до написання швидких і елегантних запитів"
baseurl: "/sql-judo"
url: "https://github.com/sql-monk"

# Theme
#remote_theme: pages-themes/midnight@v0.2.0

# Plugins
#plugins:
#  - jekyll-remote-theme
#  - jekyll-feed
#  - jekyll-sitemap

markdown: kramdown
# highlighter: rouge
# kramdown:
#  input: GFM
#  syntax_highlighter: rouge

# Exclude files
exclude:
  - README.md
  - docs/
  - plan*.md
